on: [pull_request]
jobs:
  build-android-development_and_add_in_pr_result:
  - runs-on: ubuntu-latest
    steps:
    - name: 🚀 Create preview
      uses: expo/expo-github-action/preview@v8
      with:
        command: echo ${{ github.event.pull_request.head.ref }}